FROM docker.io/library/debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates curl gnupg \
 && curl -SsL https://playit-cloud.github.io/ppa/key.gpg \
    | gpg --dearmor \
    > /etc/apt/trusted.gpg.d/playit.gpg \
 && echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" \
    > /etc/apt/sources.list.d/playit-cloud.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends playit \
 && rm -rf /var/lib/apt/lists/*

COPY playit-entrypoint.sh /usr/local/bin/playit-entrypoint.sh
RUN chmod +x /usr/local/bin/playit-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/playit-entrypoint.sh"]
